/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frexal
 */
public class jfdDocentes extends javax.swing.JDialog {
    
    public DefaultComboBoxModel dcmBusqueda;
    public DefaultComboBoxModel dcmCalendario;
    public DefaultTableModel dtmDocentes;
    public DefaultTableModel dtmMaterias;
    public SpinnerDateModel sdmHoraIni;
    public SpinnerDateModel sdmHoraFin;

    /**
     * Creates new form jfdDocentes
     */
    public jfdDocentes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        dcmBusqueda =  new DefaultComboBoxModel();
        dcmCalendario = new DefaultComboBoxModel();
        dtmDocentes = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                    return false;
            }
        };
        dtmMaterias = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                    return false;
            }
        };
        
        Date date = new Date();
        sdmHoraIni = new SpinnerDateModel(date, null, null, Calendar.MINUTE);
        sdmHoraFin = new SpinnerDateModel(date, null, null, Calendar.MINUTE);
        initComponents();
        JSpinner.DateEditor de = new JSpinner.DateEditor(spiHoraIni, "HH:mm:ss");
        de.getTextField().setEditable(false);
        spiHoraIni.setEditor(de);
        JSpinner.DateEditor de2 = new JSpinner.DateEditor(spiHoraFin, "HH:mm:ss");
        de2.getTextField().setEditable(false);
        spiHoraFin.setEditor(de2);
        
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpDocentes = new javax.swing.JPanel();
        txtIdDocente = new javax.swing.JTextField();
        lblIdDocente = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApPaterno = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        lblApMaterno = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblComentarioDocente = new javax.swing.JLabel();
        jspComentarioDocente = new javax.swing.JScrollPane();
        txtComentarioDocente = new javax.swing.JTextArea();
        jtbHerramientas = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnDocentes = new javax.swing.JToggleButton();
        btnMaterias = new javax.swing.JToggleButton();
        jpListadoDocentes = new javax.swing.JPanel();
        jspListadoDocentes = new javax.swing.JScrollPane();
        tblListadoDocentes = new javax.swing.JTable();
        jpBusqueda = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JButton();
        lblBusqueda = new javax.swing.JLabel();
        cmbBusqueda = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        jpListadoMaterias = new javax.swing.JPanel();
        jspListadoMaterias = new javax.swing.JScrollPane();
        tblListadoMaterias = new javax.swing.JTable();
        jpMaterias = new javax.swing.JPanel();
        lblCRN = new javax.swing.JLabel();
        txtCRN = new javax.swing.JTextField();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblDia = new javax.swing.JLabel();
        cmbDia = new javax.swing.JComboBox<>();
        lblHoraEntrada = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblCalendario = new javax.swing.JLabel();
        cmbCalendario = new javax.swing.JComboBox<>();
        jspComentarioMateria = new javax.swing.JScrollPane();
        txtComentarioMateria = new javax.swing.JTextArea();
        lblComentarioMateria = new javax.swing.JLabel();
        spiHoraIni = new javax.swing.JSpinner();
        spiHoraFin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpDocentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Docentes"));
        jpDocentes.setToolTipText("");
        jpDocentes.setName(""); // NOI18N

        lblIdDocente.setText("ID Docente :");

        lblNombre.setText("Nombre :");

        lblApPaterno.setText("Apeido Paterno :");

        lblApMaterno.setText("Apeido Materno :");

        lblEstado.setText("Estado :");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));

        lblComentarioDocente.setText("Comentario:");

        txtComentarioDocente.setColumns(20);
        txtComentarioDocente.setRows(5);
        jspComentarioDocente.setViewportView(txtComentarioDocente);

        javax.swing.GroupLayout jpDocentesLayout = new javax.swing.GroupLayout(jpDocentes);
        jpDocentes.setLayout(jpDocentesLayout);
        jpDocentesLayout.setHorizontalGroup(
            jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDocentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDocentesLayout.createSequentialGroup()
                        .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApMaterno)
                            .addComponent(lblEstado)
                            .addComponent(lblNombre)
                            .addComponent(lblIdDocente)
                            .addComponent(lblComentarioDocente)
                            .addComponent(lblApPaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdDocente)
                            .addComponent(txtNombre)
                            .addComponent(txtApPaterno)
                            .addComponent(txtApMaterno)
                            .addGroup(jpDocentesLayout.createSequentialGroup()
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jspComentarioDocente))
                .addContainerGap())
        );
        jpDocentesLayout.setVerticalGroup(
            jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDocentesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblComentarioDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspComentarioDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jtbHerramientas.setFloatable(false);
        jtbHerramientas.setRollover(true);

        btnAgregar.setText("Agregar");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnAgregar);

        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnEditar);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnGuardar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnEliminar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnCancelar);
        jtbHerramientas.add(jSeparator1);

        btnDocentes.setSelected(true);
        btnDocentes.setText("Docentes");
        btnDocentes.setFocusable(false);
        btnDocentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDocentes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnDocentes);

        btnMaterias.setText("Materias");
        btnMaterias.setEnabled(false);
        btnMaterias.setFocusable(false);
        btnMaterias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMaterias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnMaterias);

        jpListadoDocentes.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Docentes"));

        jspListadoDocentes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jspListadoDocentes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspListadoDocentes.setAutoscrolls(true);

        tblListadoDocentes.setModel(dtmDocentes);
        tblListadoDocentes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jspListadoDocentes.setViewportView(tblListadoDocentes);

        javax.swing.GroupLayout jpListadoDocentesLayout = new javax.swing.GroupLayout(jpListadoDocentes);
        jpListadoDocentes.setLayout(jpListadoDocentesLayout);
        jpListadoDocentesLayout.setHorizontalGroup(
            jpListadoDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoDocentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoDocentes)
                .addContainerGap())
        );
        jpListadoDocentesLayout.setVerticalGroup(
            jpListadoDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoDocentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        btnBusqueda.setText("Busqueda");

        lblBusqueda.setText("Busqueda por :");

        cmbBusqueda.setModel(dcmBusqueda);

        javax.swing.GroupLayout jpBusquedaLayout = new javax.swing.GroupLayout(jpBusqueda);
        jpBusqueda.setLayout(jpBusquedaLayout);
        jpBusquedaLayout.setHorizontalGroup(
            jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBusquedaLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblBusqueda)
                .addGap(18, 18, 18)
                .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBusqueda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBusquedaLayout.setVerticalGroup(
            jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBusquedaLayout.createSequentialGroup()
                .addGroup(jpBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBusqueda)
                    .addComponent(lblBusqueda)
                    .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jpListadoMaterias.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias por Docente"));

        jspListadoMaterias.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jspListadoMaterias.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspListadoMaterias.setAutoscrolls(true);

        tblListadoMaterias.setModel(dtmMaterias);
        tblListadoMaterias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jspListadoMaterias.setViewportView(tblListadoMaterias);

        javax.swing.GroupLayout jpListadoMateriasLayout = new javax.swing.GroupLayout(jpListadoMaterias);
        jpListadoMaterias.setLayout(jpListadoMateriasLayout);
        jpListadoMateriasLayout.setHorizontalGroup(
            jpListadoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoMaterias)
                .addContainerGap())
        );
        jpListadoMateriasLayout.setVerticalGroup(
            jpListadoMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpListadoMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpMaterias.setBorder(javax.swing.BorderFactory.createTitledBorder("Materias"));

        lblCRN.setText("CRN :");

        lblDescripcion.setText("Descripción :");

        lblDia.setText("Dia :");

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));
        cmbDia.setSelectedIndex(1);

        lblHoraEntrada.setText("Hora Entrada :");

        lblHoraSalida.setText("Hora Salida :");

        lblGrupo.setText("Grupo :");

        lblCalendario.setText("Calendario");

        cmbCalendario.setModel(dcmCalendario);

        txtComentarioMateria.setColumns(20);
        txtComentarioMateria.setRows(5);
        jspComentarioMateria.setViewportView(txtComentarioMateria);

        lblComentarioMateria.setText("Comentario:");

        spiHoraIni.setModel(sdmHoraIni);

        spiHoraFin.setModel(sdmHoraFin);

        javax.swing.GroupLayout jpMateriasLayout = new javax.swing.GroupLayout(jpMaterias);
        jpMaterias.setLayout(jpMateriasLayout);
        jpMateriasLayout.setHorizontalGroup(
            jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMateriasLayout.createSequentialGroup()
                        .addComponent(lblComentarioMateria)
                        .addGap(155, 155, 155))
                    .addGroup(jpMateriasLayout.createSequentialGroup()
                        .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMateriasLayout.createSequentialGroup()
                                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCRN)
                                    .addComponent(lblDescripcion)
                                    .addComponent(lblDia)
                                    .addComponent(lblCalendario)
                                    .addComponent(lblGrupo))
                                .addGap(28, 28, 28)
                                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCRN)
                                    .addComponent(txtDescripcion)
                                    .addGroup(jpMateriasLayout.createSequentialGroup()
                                        .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtGrupo)))
                            .addComponent(jspComentarioMateria)
                            .addGroup(jpMateriasLayout.createSequentialGroup()
                                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraEntrada)
                                    .addComponent(lblHoraSalida))
                                .addGap(28, 28, 28)
                                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spiHoraFin)
                                    .addComponent(spiHoraIni))))
                        .addContainerGap())))
        );
        jpMateriasLayout.setVerticalGroup(
            jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriasLayout.createSequentialGroup()
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCRN, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentarioMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspComentarioMateria)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpListadoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpListadoDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtbHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpDocentes, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpListadoDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpListadoMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBusqueda;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JToggleButton btnDocentes;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JToggleButton btnMaterias;
    public javax.swing.JComboBox<String> cmbBusqueda;
    public javax.swing.JComboBox<String> cmbCalendario;
    public javax.swing.JComboBox<String> cmbDia;
    public javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JToolBar.Separator jSeparator1;
    public javax.swing.JPanel jpBusqueda;
    public javax.swing.JPanel jpDocentes;
    public javax.swing.JPanel jpListadoDocentes;
    public javax.swing.JPanel jpListadoMaterias;
    public javax.swing.JPanel jpMaterias;
    private javax.swing.JScrollPane jspComentarioDocente;
    private javax.swing.JScrollPane jspComentarioMateria;
    public javax.swing.JScrollPane jspListadoDocentes;
    public javax.swing.JScrollPane jspListadoMaterias;
    public javax.swing.JToolBar jtbHerramientas;
    public javax.swing.JLabel lblApMaterno;
    public javax.swing.JLabel lblApPaterno;
    public javax.swing.JLabel lblBusqueda;
    public javax.swing.JLabel lblCRN;
    public javax.swing.JLabel lblCalendario;
    public javax.swing.JLabel lblComentarioDocente;
    public javax.swing.JLabel lblComentarioMateria;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblDia;
    public javax.swing.JLabel lblEstado;
    public javax.swing.JLabel lblGrupo;
    public javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    public javax.swing.JLabel lblIdDocente;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JSpinner spiHoraFin;
    public javax.swing.JSpinner spiHoraIni;
    public javax.swing.JTable tblListadoDocentes;
    public javax.swing.JTable tblListadoMaterias;
    public javax.swing.JTextField txtApMaterno;
    public javax.swing.JTextField txtApPaterno;
    public javax.swing.JTextField txtBusqueda;
    public javax.swing.JTextField txtCRN;
    public javax.swing.JTextArea txtComentarioDocente;
    public javax.swing.JTextArea txtComentarioMateria;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtGrupo;
    public javax.swing.JTextField txtIdDocente;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
