/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Frexal
 */
public class jfdEditMaterias extends javax.swing.JDialog {

    public DefaultComboBoxModel dcmDocentes;
    public DefaultComboBoxModel dcmCRN;
    public DefaultComboBoxModel dcmCalendario;
    public DefaultTableModel dtmMateriaDocentes;
    public DefaultTableModel dtmMaterias;
    public SpinnerDateModel sdmHoraIni;
    public SpinnerDateModel sdmHoraFin;
    
    /**
     * Creates new form jfdEditMaterias
     */
    public jfdEditMaterias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //Iniciacion de Modelos para uso de Datos
        dcmDocentes =  new DefaultComboBoxModel();
        dcmCRN =  new DefaultComboBoxModel();
        dcmCalendario =  new DefaultComboBoxModel();
        
        dtmMateriaDocentes = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                    return false;
            }
        };
        dtmMaterias = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                    return false;
            }
        };
        
        Date date = new Date();
        sdmHoraIni = new SpinnerDateModel(date, null, null, Calendar.MINUTE);
        sdmHoraFin = new SpinnerDateModel(date, null, null, Calendar.MINUTE);
        initComponents();
        JSpinner.DateEditor de = new JSpinner.DateEditor(spiHoraIni, "HH:mm:ss");
        de.getTextField().setEditable(false);
        spiHoraIni.setEditor(de);
        JSpinner.DateEditor de2 = new JSpinner.DateEditor(spiHoraFin, "HH:mm:ss");
        de2.getTextField().setEditable(false);
        spiHoraFin.setEditor(de2);
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbHerramientas = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblBanDocente = new javax.swing.JLabel();
        jtpMaterias = new javax.swing.JTabbedPane();
        jpMateria = new javax.swing.JPanel();
        jpEditMateria = new javax.swing.JPanel();
        txtCRN = new javax.swing.JTextField();
        lblCRN = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jpListadoMateria = new javax.swing.JPanel();
        jspListadoMaterias = new javax.swing.JScrollPane();
        tblListadoMaterias = new javax.swing.JTable();
        jpBusquedaMateria = new javax.swing.JPanel();
        btnBusquedaMateria = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbBusquedaMateria = new javax.swing.JComboBox<>();
        txtBusquedaMateria = new javax.swing.JTextField();
        jpMateriaDocente = new javax.swing.JPanel();
        jpFiltroMateriaDocente = new javax.swing.JPanel();
        cmbFiltroDocente = new javax.swing.JComboBox<>();
        lblFiltroDocente = new javax.swing.JLabel();
        btnBuscarMateriasDocente = new javax.swing.JButton();
        jpEditarMateriaDocente = new javax.swing.JPanel();
        lblCRNMateriaDocente = new javax.swing.JLabel();
        lblDescripcionMateriaDocente = new javax.swing.JLabel();
        txtDescripcionMateriaDocente = new javax.swing.JTextField();
        lblDia = new javax.swing.JLabel();
        lblCalendario = new javax.swing.JLabel();
        cmbCalendario = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        lblFechaInicio = new javax.swing.JLabel();
        jdcFechaInicio = new com.toedter.calendar.JDateChooser();
        cmbCRNMateriaDocente = new javax.swing.JComboBox<>();
        lblFechaFin = new javax.swing.JLabel();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        lblGrupo = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        lblHoraEntrada = new javax.swing.JLabel();
        spiHoraIni = new javax.swing.JSpinner();
        lblHoraSalida = new javax.swing.JLabel();
        spiHoraFin = new javax.swing.JSpinner();
        lblComentarioMateria = new javax.swing.JLabel();
        jspComentarioMateria = new javax.swing.JScrollPane();
        txtComentarioMateria = new javax.swing.JTextArea();
        jpListadoMateriaDocente = new javax.swing.JPanel();
        jspListadoMateriaDocente = new javax.swing.JScrollPane();
        tblListadoMateriaDocente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jtbHerramientas.setFloatable(false);
        jtbHerramientas.setRollover(true);

        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnNuevo);

        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnEditar);

        btnGuardar.setText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnGuardar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnEliminar);

        btnCancelar.setText("Cancelar");
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbHerramientas.add(btnCancelar);
        jtbHerramientas.add(lblBanDocente);

        jpEditMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Materia"));

        lblCRN.setText("CRN :");

        lblNombre.setText("Nombre :");

        lblEstado.setText("Estado :");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));

        javax.swing.GroupLayout jpEditMateriaLayout = new javax.swing.GroupLayout(jpEditMateria);
        jpEditMateria.setLayout(jpEditMateriaLayout);
        jpEditMateriaLayout.setHorizontalGroup(
            jpEditMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbEstado, 0, 134, Short.MAX_VALUE)
                    .addComponent(txtCRN, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpEditMateriaLayout.createSequentialGroup()
                        .addGroup(jpEditMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCRN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpEditMateriaLayout.setVerticalGroup(
            jpEditMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditMateriaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblCRN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCRN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jpListadoMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Materias"));

        jspListadoMaterias.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jspListadoMaterias.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspListadoMaterias.setAutoscrolls(true);

        tblListadoMaterias.setModel(dtmMaterias);
        tblListadoMaterias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jspListadoMaterias.setViewportView(tblListadoMaterias);

        javax.swing.GroupLayout jpListadoMateriaLayout = new javax.swing.GroupLayout(jpListadoMateria);
        jpListadoMateria.setLayout(jpListadoMateriaLayout);
        jpListadoMateriaLayout.setHorizontalGroup(
            jpListadoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoMaterias)
                .addContainerGap())
        );
        jpListadoMateriaLayout.setVerticalGroup(
            jpListadoMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListadoMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspListadoMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpBusquedaMateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        btnBusquedaMateria.setText("Busqueda");

        jLabel1.setText("Filtro :");

        cmbBusquedaMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRN", "NOMBRE" }));

        javax.swing.GroupLayout jpBusquedaMateriaLayout = new javax.swing.GroupLayout(jpBusquedaMateria);
        jpBusquedaMateria.setLayout(jpBusquedaMateriaLayout);
        jpBusquedaMateriaLayout.setHorizontalGroup(
            jpBusquedaMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBusquedaMateriaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBusquedaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusquedaMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBusquedaMateria)
                .addGap(83, 83, 83))
        );
        jpBusquedaMateriaLayout.setVerticalGroup(
            jpBusquedaMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBusquedaMateriaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpBusquedaMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpBusquedaMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbBusquedaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBusquedaMateria))
                    .addComponent(txtBusquedaMateria))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpMateriaLayout = new javax.swing.GroupLayout(jpMateria);
        jpMateria.setLayout(jpMateriaLayout);
        jpMateriaLayout.setHorizontalGroup(
            jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpBusquedaMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMateriaLayout.createSequentialGroup()
                        .addComponent(jpEditMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpListadoMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMateriaLayout.setVerticalGroup(
            jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpBusquedaMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEditMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpListadoMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpMaterias.addTab("Materias (CRN)", jpMateria);

        jpFiltroMateriaDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Docente"));

        cmbFiltroDocente.setModel(dcmDocentes);

        lblFiltroDocente.setText("Docente");

        btnBuscarMateriasDocente.setText("Buscar Materias");

        javax.swing.GroupLayout jpFiltroMateriaDocenteLayout = new javax.swing.GroupLayout(jpFiltroMateriaDocente);
        jpFiltroMateriaDocente.setLayout(jpFiltroMateriaDocenteLayout);
        jpFiltroMateriaDocenteLayout.setHorizontalGroup(
            jpFiltroMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltroMateriaDocenteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblFiltroDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbFiltroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarMateriasDocente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFiltroMateriaDocenteLayout.setVerticalGroup(
            jpFiltroMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFiltroMateriaDocenteLayout.createSequentialGroup()
                .addGroup(jpFiltroMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFiltroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFiltroDocente)
                    .addComponent(btnBuscarMateriasDocente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEditarMateriaDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Materia"));

        lblCRNMateriaDocente.setText("CRN :");

        lblDescripcionMateriaDocente.setText("Descripcion :");

        txtDescripcionMateriaDocente.setEditable(false);
        txtDescripcionMateriaDocente.setToolTipText("");

        lblDia.setText("Dia :");

        lblCalendario.setText("Calendario :");

        cmbCalendario.setModel(dcmCalendario);
        cmbCalendario.setEnabled(false);

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        lblFechaInicio.setText("Fecha Inicio :");

        jdcFechaInicio.setDateFormatString("dd/MM/yyyy");

        cmbCRNMateriaDocente.setModel(dcmCRN);

        lblFechaFin.setText("Fecha Fin :");

        jdcFechaFin.setDateFormatString("dd/MM/yyyy");

        lblGrupo.setText("Grupo :");

        lblHoraEntrada.setText("Hora Entrada :");

        spiHoraIni.setModel(sdmHoraIni);

        lblHoraSalida.setText("Hora Salida :");

        spiHoraFin.setModel(sdmHoraFin);

        lblComentarioMateria.setText("Comentario:");

        txtComentarioMateria.setColumns(20);
        txtComentarioMateria.setRows(5);
        jspComentarioMateria.setViewportView(txtComentarioMateria);

        javax.swing.GroupLayout jpEditarMateriaDocenteLayout = new javax.swing.GroupLayout(jpEditarMateriaDocente);
        jpEditarMateriaDocente.setLayout(jpEditarMateriaDocenteLayout);
        jpEditarMateriaDocenteLayout.setHorizontalGroup(
            jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarMateriaDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditarMateriaDocenteLayout.createSequentialGroup()
                        .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcionMateriaDocente)
                            .addComponent(lblCRNMateriaDocente)
                            .addComponent(lblDia)
                            .addComponent(lblCalendario)
                            .addComponent(lblFechaInicio)
                            .addComponent(lblFechaFin)
                            .addComponent(lblGrupo))
                        .addGap(18, 18, 18)
                        .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcionMateriaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(cmbCalendario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbCRNMateriaDocente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditarMateriaDocenteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcFechaInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdcFechaFin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtGrupo)))
                    .addGroup(jpEditarMateriaDocenteLayout.createSequentialGroup()
                        .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoraEntrada)
                            .addComponent(lblHoraSalida))
                        .addGap(28, 28, 28)
                        .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spiHoraFin)
                            .addComponent(spiHoraIni)))
                    .addGroup(jpEditarMateriaDocenteLayout.createSequentialGroup()
                        .addComponent(lblComentarioMateria)
                        .addGap(145, 145, 145))
                    .addComponent(jspComentarioMateria))
                .addContainerGap())
        );
        jpEditarMateriaDocenteLayout.setVerticalGroup(
            jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarMateriaDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCRNMateriaDocente)
                    .addComponent(cmbCRNMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionMateriaDocente)
                    .addComponent(txtDescripcionMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDia)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalendario)
                    .addComponent(cmbCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaInicio)
                    .addComponent(jdcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFechaFin)
                    .addComponent(jdcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrupo)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiHoraIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentarioMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspComentarioMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpListadoMateriaDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado Materias"));

        jspListadoMateriaDocente.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jspListadoMateriaDocente.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspListadoMateriaDocente.setAutoscrolls(true);

        tblListadoMateriaDocente.setModel(dtmMateriaDocentes);
        tblListadoMateriaDocente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jspListadoMateriaDocente.setViewportView(tblListadoMateriaDocente);

        javax.swing.GroupLayout jpListadoMateriaDocenteLayout = new javax.swing.GroupLayout(jpListadoMateriaDocente);
        jpListadoMateriaDocente.setLayout(jpListadoMateriaDocenteLayout);
        jpListadoMateriaDocenteLayout.setHorizontalGroup(
            jpListadoMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspListadoMateriaDocente)
        );
        jpListadoMateriaDocenteLayout.setVerticalGroup(
            jpListadoMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspListadoMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpMateriaDocenteLayout = new javax.swing.GroupLayout(jpMateriaDocente);
        jpMateriaDocente.setLayout(jpMateriaDocenteLayout);
        jpMateriaDocenteLayout.setHorizontalGroup(
            jpMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriaDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpFiltroMateriaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpMateriaDocenteLayout.createSequentialGroup()
                        .addComponent(jpEditarMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpListadoMateriaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpMateriaDocenteLayout.setVerticalGroup(
            jpMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMateriaDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFiltroMateriaDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMateriaDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpListadoMateriaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEditarMateriaDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtpMaterias.addTab("Materia Docente", jpMateriaDocente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMaterias)
                .addContainerGap())
            .addComponent(jtbHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtbHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtpMaterias)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarMateriasDocente;
    public javax.swing.JButton btnBusquedaMateria;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cmbBusquedaMateria;
    public javax.swing.JComboBox<String> cmbCRNMateriaDocente;
    public javax.swing.JComboBox<String> cmbCalendario;
    public javax.swing.JComboBox<String> cmbDia;
    public javax.swing.JComboBox<String> cmbEstado;
    public javax.swing.JComboBox<String> cmbFiltroDocente;
    private javax.swing.JLabel jLabel1;
    public com.toedter.calendar.JDateChooser jdcFechaFin;
    public com.toedter.calendar.JDateChooser jdcFechaInicio;
    public javax.swing.JPanel jpBusquedaMateria;
    public javax.swing.JPanel jpEditMateria;
    public javax.swing.JPanel jpEditarMateriaDocente;
    public javax.swing.JPanel jpFiltroMateriaDocente;
    public javax.swing.JPanel jpListadoMateria;
    public javax.swing.JPanel jpListadoMateriaDocente;
    public javax.swing.JPanel jpMateria;
    public javax.swing.JPanel jpMateriaDocente;
    private javax.swing.JScrollPane jspComentarioMateria;
    public javax.swing.JScrollPane jspListadoMateriaDocente;
    public javax.swing.JScrollPane jspListadoMaterias;
    public javax.swing.JToolBar jtbHerramientas;
    public javax.swing.JTabbedPane jtpMaterias;
    public javax.swing.JLabel lblBanDocente;
    private javax.swing.JLabel lblCRN;
    private javax.swing.JLabel lblCRNMateriaDocente;
    private javax.swing.JLabel lblCalendario;
    private javax.swing.JLabel lblComentarioMateria;
    private javax.swing.JLabel lblDescripcionMateriaDocente;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaFin;
    public javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFiltroDocente;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblHoraEntrada;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblNombre;
    public javax.swing.JSpinner spiHoraFin;
    public javax.swing.JSpinner spiHoraIni;
    public javax.swing.JTable tblListadoMateriaDocente;
    public javax.swing.JTable tblListadoMaterias;
    public javax.swing.JTextField txtBusquedaMateria;
    public javax.swing.JTextField txtCRN;
    public javax.swing.JTextArea txtComentarioMateria;
    public javax.swing.JTextField txtDescripcionMateriaDocente;
    public javax.swing.JTextField txtGrupo;
    public javax.swing.JTextField txtNombreMateria;
    // End of variables declaration//GEN-END:variables
}
